### ISSUE TITLE
Fatal Error after installation Magento 2.0.9

### ISSUE THREAD

**Issue by derrtas** [ubertheme/module-ubdatamigration#34]
Hi

After i installed extension i got fatal error below: Any idea how to sort the problem?

Fatal error: Uncaught exception 'Magento\Framework\Exception\LocalizedException' with message 'Can't create directory /home/pashiminatest/public_html/var/generation/Magento/Framework/App/ResourceConnection/.' in /home/pashiminatest/public_html/vendor/magento/framework/Code/Generator.php:103 Stack trace: #0 /home/pashiminatest/public_html/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Magento\\Framewo...') #1 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Magento\\Framewo...') #2 [internal function]: spl_autoload_call('Magento\\Framewo...') #3 /home/pashiminatest/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...') #4 /home/pashiminatest/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...') #5 /home/pashiminatest/public_html/vendor/magento/framework/ObjectManager/Fa in /home/pashiminatest/public_html/vendor/magento/framework/Code/Generator.php on line 103

**Comment by UberthemeTeam** [comment]
Hi @derrtas ,
Thanks for spending time working with our data migration tool. 
As we recently decided to upgrade our free migration tool to a premium version — [UB Data Migration Pro](http://bit.ly/UB-data-migration-pro-release), please consider to use this newer version for a better, stable and more feature-rich solution. 

We have a [9-minute tutorial video](https://youtu.be/Jvr8d3OeB8M) that walks you through all steps using this new migration tool to handle your Magento 2 data migration.

Please take a look and see if the tool is a good fit for your project.

Regards,
Ubertheme team

**Comment by derrtas** [comment]
Hi


Thanks for your quick response. I'll give it a go.


________________________________

**Comment by UberthemeTeam** [comment]
Hi @derrtas , in case you have any additional question, please reach us here or in our helpdesk: https://www.ubertheme.com/questions/. Our team will get back to you. 
Regards,
Ubertheme team
