### ISSUE TITLE
Error checkout after migrate

### ISSUE THREAD

**Issue by balack** [ubertheme/module-ubdatamigration#7]
After migrate success, I'm test checkout product and error :  http://pasteboard.co/O8rPR5k.png

And logs: 

[2016-01-15 08:49:03] main.CRITICAL: exception 'Zend_Db_Statement_Exception' with message 'Report ID: webapi-5698b27f9bb41; Message: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '', query was: INSERT INTO `` () VALUES ()' in /var/www/html/magento20new/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:194
Stack trace:
#0 /var/www/html/magento20new/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Zend_Db_Statement_Exception))
#1 /var/www/html/magento20new/app/code/Magento/Webapi/Controller/Rest.php(163): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Zend_Db_Statement_Exception))
#2 /var/www/html/magento20new/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento20new/lib/internal/Magento/Framework/App/Http.php(115): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento20new/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/magento20new/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

Can you help me? pls

**Comment by quynhvv** [comment]
@balack

That issue because have some new work flow of sales module in Magento 2.
and your database migrated is multiple stores
and it's missing needed tables for module-sales and module-sales-sequence.
You can see more at this: http://i.imgur.com/rkFvbC8.png
=> That are initial tables after you install a fresh Magento 2.
and after migrate data with this tool, you database was missing some tables for other stores (not default store)
See more: https://mage2.pro/t/topic/511

Regards,
Mall.

**Comment by philipvandebriel** [comment]
Hi,
I get the same error in 2.0.0 and 2.0.2 , what is the solution ?
regards,

Philip

`[2016-02-11 13:09:47] main.CRITICAL: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''' in /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/clients/client1/web1/web/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `` ...', Array)
#5 /var/www/clients/client1/web1/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(444): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `` ...', Array)
#6 /var/www/clients/client1/web1/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(499): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('INSERT INTO `` ...', Array)
#7 /var/www/clients/client1/web1/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(576): Magento\Framework\DB\Adapter\Pdo\Mysql->query('INSERT INTO `` ...', Array)
#8 /var/www/clients/client1/web1/web/vendor/magento/module-sales-sequence/Model/Sequence.php(82): Zend_Db_Adapter_Abstract->insert(NULL, Array)
#9 /var/www/clients/client1/web1/web/vendor/magento/module-quote/Model/ResourceModel/Quote.php(170): Magento\SalesSequence\Model\Sequence->getNextValue()
#10 /var/www/clients/client1/web1/web/vendor/magento/module-quote/Model/Quote.php(2157): Magento\Quote\Model\ResourceModel\Quote->getReservedOrderId(Object(Magento\Quote\Model\Quote))
#11 /var/www/clients/client1/web1/web/vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php(602): Magento\Quote\Model\Quote->reserveOrderId()
#12 /var/www/clients/client1/web1/web/vendor/magento/module-multishipping/Model/Checkout/Type/Multishipping.php(694): Magento\Multishipping\Model\Checkout\Type\Multishipping->_prepareOrder(Object(Magento\Quote\Model\Quote\Address))
#13 /var/www/clients/client1/web1/web/var/generation/Magento/Multishipping/Model/Checkout/Type/Multishipping/Interceptor.php(116): Magento\Multishipping\Model\Checkout\Type\Multishipping->createOrders()
#14 /var/www/clients/client1/web1/web/vendor/magento/module-multishipping/Controller/Checkout/OverviewPost.php(95): Magento\Multishipping\Model\Checkout\Type\Multishipping\Interceptor->createOrders()
#15 /var/www/clients/client1/web1/web/var/generation/Magento/Multishipping`

**Comment by philipvandebriel** [comment]
Hi,
I have the tables in my database,
![schermafdruk 2016-02-12 10 23 14](https://cloud.githubusercontent.com/assets/15958461/13002965/cda78e08-d172-11e5-8e3a-ec41272e16a5.png)

Regards,
Philip

**Comment by quynhvv** [comment]
@philipvandebriel 
Thanks for working around this tool, hope it could help you some way.
As data migration itself is a complex task as it relates to different factors including the server condition etc., we do provide migration custom service. Just add a note here, in case you might want to use our service.
https://www.ubertheme.com/magento-custom-services/

Regards,
Mall.

**Comment by ManishEbiz** [comment]
**@quynhvv **

I'm also facing this issue. Do you have any idea, how to resolve this.??
Is this issue comes after migration or default magento 2.0  have this issue ??

Please help me.

Thanks

**Comment by philipvandebriel** [comment]
Yes you missing some tables in your store view because you have more then 2 store views. In phpmyadmin, you can make new sequence_...... tables for every storeview. After the error is away because the backend need to write the ordernumber, invoicenumber etc... to every storeview.

**Comment by ManishEbiz** [comment]
@philipvandebriel:

Thanks for the reply, but can you please let me know is this default magento2 issue, or this issue comes after data migration??

Also the new table 'sequence_'   is define in table *sales_sequence_meta * (see column sequence_table) 
![sales_sequence_meta](https://cloud.githubusercontent.com/assets/16588268/14080320/e0876c50-f521-11e5-80ba-78911981858a.png)

In this table also there is column of **meta_id**.

This meta_id is define in the '**sales_sequence_profile**'.

So i have one doubt:  to create new table sequence_ for every store is that required to fill up the information in table 'sales_sequence_meta' and 'sales_sequence_profile'?? If yes then what will be the profile id?? 

Thanks for you reply.
